package com.hyenawarrior.OldNorseGrammar.grammar.nouns

import com.hyenawarrior.OldNorseGrammar.grammar.morphophonology.ProductiveTransforms.{ConsonantAssimilation, StressShift}
import com.hyenawarrior.OldNorseGrammar.grammar.morphophonology.StemTransform.{FixJAugmentation, FixVAugmentation}
import com.hyenawarrior.OldNorseGrammar.grammar.morphophonology.{U_Umlaut, Umlaut}
import com.hyenawarrior.OldNorseGrammar.grammar.nouns
import com.hyenawarrior.OldNorseGrammar.grammar.nouns.stemclasses.NounStemClass

/**
  * Created by HyenaWarrior on 2018.01.31..
  */
case class NounStem(rootStr: String, stemClass: NounStemClass)

object NounStem {

  def from(nounForm: NounForm, stemClass: NounStemClass): NounStem = {

    val indefNounForm = CliticArticle.removeArticle(nounForm, stemClass).getOrElse(nounForm).strRepr

    // undo consonant assimilation
    val consAssimilatedStrs = ConsonantAssimilation invert indefNounForm

    // remove inflectional ending and clitic
    val uninflectedStrs = consAssimilatedStrs
      .map(_ -> nounForm.declension)
      .flatMap {

        case stemClass(ustr) => Some(ustr)
        case _ => None
      }

    // reverse-SVD should be done here?

    // try to continue the process by choosing the first string
    uninflectedStrs.headOption match {

      case Some(uninflectedStr) => extractStemFrom(nounForm, stemClass, uninflectedStr)
      case None =>
        val inflectionalEnding = stemClass inflection nounForm.declension
        throw new RuntimeException(s"Word '${nounForm.strRepr}' doesn't have inflectional ending of $inflectionalEnding.")
    }
  }

  private def extractStemFrom(nounForm: NounForm, stemClass: NounStemClass, uninflectedStr: String): NounStem = {

    /*
      // stem -> form
      kné + um  // add inflection
      knéum     // do stress shift, it doesn't try to modify the 'u', so we have an extra vowel
      knjáum    // which is eliminated here vowel deletion
      knjám

      // form -> stem
	    knjám      // remove inflectional ending by special VD-aware stripSuffix in stemClass()
	    knjá + um  // reverse stress shift, but VD removed the 'u' of 'um'
	    knéa + um  // <!> the last 'a' letter is generated by apply, but not removed by unapply
	    kné + um

	    // desired, but incorrect option: form -> stem
	    knjám    // undo stress shift
	    knéam    // remove inflection by special VD-aware stripSuffix
	      // aargh: a+um > am not possible, as 'a' is non-labial, but á+um > ám is ok, as 'á' is labial, see VD
	    kné + um
     */

    // undo stress-shift
    val strBeforeStressShift = uninflectedStr match {

      case StressShift(str) => str.dropRight(1) // unapply of StressShift doesn't drop the extra vowel of 'j'
      case s => s
    }

    // reverse U-umlaut
    val (stemUnUmlautedStr, optUmlaut) = strBeforeStressShift match {

      case U_Umlaut(s) if strBeforeStressShift != s =>

        val inflectionalEnding = stemClass inflection nounForm.declension
        val isLocallyTriggeredUmlaut = nouns.theseCanCauseUUmlaut(inflectionalEnding)
        val isNonProductiveUmlaut = stemClass.transformationFor(nounForm.declension).contains(U_Umlaut)

        val globalUmlaut = if (isNonProductiveUmlaut || isLocallyTriggeredUmlaut) None else Some(U_Umlaut)
        s -> globalUmlaut

      case s => s -> None
    }

    // if optUmlaut!=None then a semivowel caused a productive umlaut mutation in every form of the noun

    //
    val rootStr = removeThematicVowel(stemUnUmlautedStr, stemClass)

    // undo SVD
    val augmentedRootStr = augment(rootStr, optUmlaut)

    // create the noun stem
    NounStem(augmentedRootStr, stemClass)
  }

  // basically it's the reverse SVD
  private def augment(stemStr: String, optUmlaut: Option[Umlaut]): String = (stemStr, optUmlaut) match {

    case (FixJAugmentation(fixedStemStr), _) => fixedStemStr
    case (FixVAugmentation(fixedStemStr), _) => fixedStemStr
    case (_, Some(U_Umlaut)) => stemStr + "v"
    case _ => stemStr
  }

  def fromStrRepr(stemStr: String, stemClass: NounStemClass): NounStem = {

    val rootStr = removeThematicVowel(stemStr, stemClass)

    NounStem(rootStr, stemClass)
  }

  def removeThematicVowel(stemStr: String, stemClass: NounStemClass): String = {

    val thematicVowel = stemClass.thematicVowel.getOrElse("")

    stemStr stripSuffix thematicVowel
  }
}